<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-07 at 14:25:57.
 */
class core_ModeTest extends PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        core_Mode::$mode = NULL;
        core_Mode::$stack = array();
    }

    /**
     * @covers core_Mode::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers core_Mode::push
     * @covers core_Mode::pop
     */
    public function testPushPopValue()
    {
        core_Mode::push('name', 'first');
        $this->assertEquals('first', core_Mode::get('name'));
        core_Mode::push('name', 'second');
        $this->assertEquals('second', core_Mode::get('name'));
        core_Mode::pop('name');
        $this->assertEquals('first', core_Mode::get('name'));
    }

    /**
     * @covers core_Mode::push
     * @covers core_Mode::pop
     * @expectedException core_Exception_Expect
     */
    public function testPushPopOrder()
    {
        core_Mode::push('first', 'a');
        core_Mode::push('second', 'b');
        
        core_Mode::pop('first');
    }

    /**
     * @covers core_Mode::push
     * @covers core_Mode::pop
     */
    public function testPopNoarg()
    {
        core_Mode::push('first', 'a1');
        core_Mode::push('first', 'a2');
        core_Mode::push('second', 'b1');
        core_Mode::push('second', 'b2');
        
        core_Mode::pop();
        $this->assertEquals('b1', core_Mode::get('second'));
        
        core_Mode::pop();
        $this->assertEquals(NULL, core_Mode::get('second'));
        
        core_Mode::pop();
        $this->assertEquals('a1', core_Mode::get('first'));
        
        core_Mode::pop();
        $this->assertEquals(NULL, core_Mode::get('first'));
    }

    /**
     * @covers core_Mode::setPermanent
     * @todo   Implement testSetPermanent().
     */
    public function testSetPermanent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers core_Mode::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers core_Mode::is
     * @todo   Implement testIs().
     */
    public function testIs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers core_Mode::getPermanentKey
     * @todo   Implement testGetPermanentKey().
     */
    public function testGetPermanentKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers core_Mode::getProcessKey
     * @todo   Implement testGetProcessKey().
     */
    public function testGetProcessKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers core_Mode::destroy
     * @todo   Implement testDestroy().
     */
    public function testDestroy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
