<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-22 at 16:51:40.
 */

require EF_APP_PATH . '/email/util/ThreadHandle.class.php';

class email_util_ThreadHandleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var email_util_ThreadHandle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new email_util_ThreadHandle;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers email_util_ThreadHandle::decorate
     */
    public function testDecorate()
    {
        $expected = '#abc12de Test Subject';
        $actual   =  email_util_ThreadHandle::decorate('Test Subject', 'abc12de');
        
        $this->assertEquals($expected, $actual);

        // Тест на избягване на двойната декорация
        $expected = '#abc12de Test Subject';
        $actual   =  email_util_ThreadHandle::decorate('#abc12de Test Subject', 'abc12de');
        
        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers email_util_ThreadHandle::strip
     * @todo   Implement testStrip().
     */
    public function testStrip()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers email_util_ThreadHandle::extract
     */
    public function testExtract()
    {
        $expected = array('ab3cdf'=>'ab3cdf');
        $actual   = email_util_ThreadHandle::extract('RE: #ab3cdf Email Subject');
        
        $this->assertEquals($expected, $actual);

        $expected = array('abc12de'=>'abc12de');
        $actual   = email_util_ThreadHandle::extract('#abc12de Test Subject');
        
        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers email_util_ThreadHandle::protect
     * @todo   Implement testProtect().
     */
    public function testProtect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers email_util_ThreadHandle::makeMessageId
     * @todo   Implement testMakeMessageId().
     */
    public function testMakeMessageId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers email_util_ThreadHandle::extractMid
     * @todo   Implement testExtractMid().
     */
    public function testExtractMid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
